version: '3'

services:
  myrevproxy:
    container_name: myrevproxy
    hostname: myrevproxy
    image: lb_nginx_container
    ports:
      - 8081:80
  mywebserver:
    container_name: mywebserver
    hostname: mywebserver
    image: web_server_container
    ports:
      - 8082:80
